FROM ubi8/ubi:8.3

MAINTAINER ysc <ysc@example.com>

ENV PORT 8080

RUN yum install -y httpd && yum clean all

RUN sed -ri -e "/^Listen 80/c\Listen 8080" /etc/httpd/conf/httpd.conf && \
    chown -R apache:apache /etc/httpd/logs/ && \
    chown -R apache:apache /run/httpd/

USER apache

# Expose the custom port that you provided in the ENV var
EXPOSE 8080

# Copy all files under src/ folder to Apache DocumentRoot (/var/www/html) 
COPY ./src/ /var/www/html/

# Start Apache in the foregroundi
CMD ["httpd", "-D", "FOREGROUND"]
